# Generated by Django 4.2.1 on 2023-06-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
                ('ConfirmPassword', models.CharField(max_length=8)),
                ('EmailId', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
            ],
        ),
    ]
